2017-04-24 12:39:49,926 INFO 787 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): localhost
2017-04-24 12:39:49,940 INFO 787 [lms.lib.comment_client.utils] utils.py:49 - comment_client_request_log: request_id=909ca3ec-711d-49c7-98ea-d52a0cd94b9f, method=put, url=http://localhost:18080/api/v1/users/28, duration=0.0144581794739
2017-04-24 12:39:50,987 INFO 787 [audit] models.py:1802 - Login success - user.id: 28
2017-04-24 12:39:51,010 INFO 787 [audit] views.py:1822 - Login success on new account creation - DaveT
2017-04-24 13:26:29,142 INFO 787 [audit] models.py:1802 - Login success - user.id: 5
2017-04-24 13:26:38,032 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_zB7ljWcEazA.srt.sjson
2017-04-24 20:44:18,015 INFO 790 [audit] models.py:1804 - Login success - mattnewlin (mnewlin@wustl.edu)
2017-04-24 21:18:25,841 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:25,892 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[af9a2472-966e-4511-a54e-4f18da33d1d6]
2017-04-24 21:18:25,939 INFO 789 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for course-v1:SkandalarisCenter+SCYC1001+SU_2017.
2017-04-24 21:18:25,949 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[af9a2472-966e-4511-a54e-4f18da33d1d6] succeeded in 0.0564784950111s: None
2017-04-24 21:18:26,007 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[a0ecd097-da8f-498a-b998-e40972c13872]
2017-04-24 21:18:26,009 INFO 1008 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:18:26,012 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,012 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,012 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,012 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,012 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,013 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:26,063 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@sequential+block@4afd86a8bfbb4fe49a3c0d9b17cbcac5
2017-04-24 21:18:26,088 INFO 1008 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:18:26,090 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[a0ecd097-da8f-498a-b998-e40972c13872] succeeded in 0.0810377770104s: None
2017-04-24 21:18:45,580 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,635 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[89de85cb-276e-4082-8ea5-1e395e03235e]
2017-04-24 21:18:45,680 INFO 789 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for course-v1:SkandalarisCenter+SCYC1001+SU_2017.
2017-04-24 21:18:45,700 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[89de85cb-276e-4082-8ea5-1e395e03235e] succeeded in 0.0631573470309s: None
2017-04-24 21:18:45,746 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[9210a9ae-87fd-4573-897f-eec522c04c8a]
2017-04-24 21:18:45,747 INFO 1006 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:18:45,750 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,750 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,751 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,751 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,751 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,751 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:18:45,794 INFO 1006 [edx.celery.task] tasks.py:117 - Updating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@sequential+block@4afd86a8bfbb4fe49a3c0d9b17cbcac5
2017-04-24 21:18:45,814 INFO 1006 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:18:45,815 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[9210a9ae-87fd-4573-897f-eec522c04c8a] succeeded in 0.0678881909698s: None
2017-04-24 21:19:05,215 WARNING 790 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:19:34,626 WARNING 789 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:20:05,102 INFO 789 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_3_yD_cEKoCk.srt.sjson
2017-04-24 21:20:10,546 WARNING 790 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:20:10,883 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:20:10,991 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:20:13,831 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:20:13,926 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:20:24,817 INFO 790 [xmodule.video_module.transcripts_utils] transcripts_utils.py:543 - Transcript asset subs_dmEdNJFpbKI.srt.sjson was removed from store.
2017-04-24 21:20:25,088 INFO 789 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_dmEdNJFpbKI.srt.sjson
2017-04-24 21:21:51,137 WARNING 790 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:24:19,165 ERROR 790 [root] exceptions.py:9 - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/djangoapps/util/json_request.py", line 52, in parse_json_into_request
    return view_function(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/cms/djangoapps/contentstore/views/item.py", line 221, in xblock_view_handler
    xblock = store.get_item(usage_key)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 90, in inner
    retval = func(field_decorator=strip_key_collection, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 268, in get_item
    return store.get_item(usage_key, depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split_draft.py", line 280, in get_item
    return super(DraftVersioningModuleStore, self).get_item(usage_key, depth=depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 1131, in get_item
    items = self._load_items(course, [BlockKey.from_usage_key(usage_key)], depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 778, in _load_items
    return [runtime.load_item(block_key, course_entry, **kwargs) for block_key in block_keys]
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 130, in _load_item
    block_data = self.get_module_data(block_key, course_key)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 151, in get_module_data
    raise ItemNotFoundError(block_key)
ItemNotFoundError: BlockKey(type=u'video', id=u'13e515cbca4445d19094e1f09afb4a29')
2017-04-24 21:24:19,183 ERROR 790 [django.request] base.py:256 - Internal Server Error: /xblock/block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@video+block@13e515cbca4445d19094e1f09afb4a29/reorderable_container_child_preview
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/djangoapps/util/json_request.py", line 52, in parse_json_into_request
    return view_function(request, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/cms/djangoapps/contentstore/views/item.py", line 221, in xblock_view_handler
    xblock = store.get_item(usage_key)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 90, in inner
    retval = func(field_decorator=strip_key_collection, *args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 268, in get_item
    return store.get_item(usage_key, depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split_draft.py", line 280, in get_item
    return super(DraftVersioningModuleStore, self).get_item(usage_key, depth=depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 1131, in get_item
    items = self._load_items(course, [BlockKey.from_usage_key(usage_key)], depth, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 778, in _load_items
    return [runtime.load_item(block_key, course_entry, **kwargs) for block_key in block_keys]
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 130, in _load_item
    block_data = self.get_module_data(block_key, course_key)
  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/caching_descriptor_system.py", line 151, in get_module_data
    raise ItemNotFoundError(block_key)
ItemNotFoundError: BlockKey(type=u'video', id=u'13e515cbca4445d19094e1f09afb4a29')
2017-04-24 21:24:31,811 INFO 790 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_3_yD_cEKoCk.srt.sjson
2017-04-24 21:24:32,986 WARNING 789 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:24:33,269 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:24:33,443 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:24:35,843 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:24:35,950 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:24:41,436 INFO 789 [xmodule.video_module.transcripts_utils] transcripts_utils.py:543 - Transcript asset subs_qrmrCl7lbKA.srt.sjson was removed from store.
2017-04-24 21:24:41,711 INFO 789 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-24 21:26:12,885 INFO 790 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_3_yD_cEKoCk.srt.sjson
2017-04-24 21:26:19,807 WARNING 789 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:26:20,119 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:26:20,297 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:26:21,566 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:26:21,628 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:26:28,335 INFO 790 [xmodule.video_module.transcripts_utils] transcripts_utils.py:543 - Transcript asset subs_yFMCovOeHhs.srt.sjson was removed from store.
2017-04-24 21:26:28,605 INFO 790 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_yFMCovOeHhs.srt.sjson
2017-04-24 21:26:47,360 INFO 789 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_3_yD_cEKoCk.srt.sjson
2017-04-24 21:27:59,079 WARNING 789 [xblock.plugin] plugin.py:147 - Unable to load XBlockAside 'thumbs_aside'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-24 21:28:00,002 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:28:00,109 INFO 790 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:28:01,446 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:28:01,548 INFO 789 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): video.google.com
2017-04-24 21:28:04,397 INFO 790 [xmodule.video_module.transcripts_utils] transcripts_utils.py:543 - Transcript asset subs_mHJlt3w4kTQ.srt.sjson was removed from store.
2017-04-24 21:28:04,983 INFO 789 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-24 21:28:22,714 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,759 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[044edabc-2775-4d60-a70e-a6b4ea58827a]
2017-04-24 21:28:22,805 INFO 789 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for course-v1:SkandalarisCenter+SCYC1001+SU_2017.
2017-04-24 21:28:22,841 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[044edabc-2775-4d60-a70e-a6b4ea58827a] succeeded in 0.0807797191665s: None
2017-04-24 21:28:22,887 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[cfa57f27-4ce9-4dff-b68c-6c50f0e3d5fc]
2017-04-24 21:28:22,888 INFO 1008 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:28:22,891 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,891 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,891 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,891 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,892 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,892 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'SkandalarisCenter', u'SCYC1001', u'SU_2017', None, None)}. Response was: None
2017-04-24 21:28:22,947 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@409383563ec0447287e5f63267d816e6
2017-04-24 21:28:22,971 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@6b3a6a637df14bf69f991eb605471a19
2017-04-24 21:28:22,996 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@video+block@f42dec77ca3f40e8a47e1172b5960a26
2017-04-24 21:28:23,022 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@0e16deaa9b4343fa93e9818221828edd
2017-04-24 21:28:23,054 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@video+block@3adb4c0ee6ea4f548629f48aa0066d78
2017-04-24 21:28:23,078 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@video+block@93afd39ef8e14935b7ac2f8c085e8a0d
2017-04-24 21:28:23,103 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@c5d876e7b7b345b59013165bd32836ee
2017-04-24 21:28:23,127 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@de8900d1e7d14060ba67cfdb931c68ce
2017-04-24 21:28:23,156 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@video+block@665db479a84343e7b0c6ba222f81e612
2017-04-24 21:28:23,181 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@vertical+block@f84418cea2554f1a89a7d09760556034
2017-04-24 21:28:23,205 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@html+block@58be6ab78c46450bad0c1a97bf91a4ea
2017-04-24 21:28:23,227 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: block-v1:SkandalarisCenter+SCYC1001+SU_2017+type@html+block@a91494923d1242f3a377d5f04f928e9c
2017-04-24 21:28:23,258 INFO 1008 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: course-v1:SkandalarisCenter+SCYC1001+SU_2017
2017-04-24 21:28:23,259 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[cfa57f27-4ce9-4dff-b68c-6c50f0e3d5fc] succeeded in 0.371188988909s: None
2017-04-24 21:29:16,537 INFO 787 [audit] models.py:1802 - Login success - user.id: 5
2017-04-24 21:29:31,291 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_zB7ljWcEazA.srt.sjson
2017-04-24 21:29:33,526 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_zB7ljWcEazA.srt.sjson
2017-04-24 21:29:37,509 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_dmEdNJFpbKI.srt.sjson
2017-04-24 21:29:42,507 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-24 21:29:44,650 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_yFMCovOeHhs.srt.sjson
2017-04-24 21:29:52,062 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-24 21:30:54,674 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-24 21:31:27,562 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_zB7ljWcEazA.srt.sjson
2017-04-24 21:31:36,786 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_zB7ljWcEazA.srt.sjson
2017-04-24 21:32:41,513 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-24 22:07:05,835 WARNING 787 [audit] views.py:1174 - Login failed - Unknown user email
2017-04-24 22:07:05,854 INFO 787 [ratelimitbackend] backends.py:44 - Login failed: username '', IP 162.158.69.157
2017-04-24 22:09:55,957 WARNING 788 [audit] views.py:1174 - Login failed - Unknown user email
2017-04-24 22:09:55,977 INFO 788 [ratelimitbackend] backends.py:44 - Login failed: username '', IP 162.158.69.157
2017-04-24 22:10:10,897 WARNING 788 [audit] views.py:1174 - Login failed - Unknown user email
2017-04-24 22:10:10,916 INFO 788 [ratelimitbackend] backends.py:44 - Login failed: username '', IP 162.158.69.157
2017-04-24 22:10:27,047 WARNING 788 [audit] views.py:1174 - Login failed - Unknown user email
2017-04-24 22:10:27,067 INFO 788 [ratelimitbackend] backends.py:44 - Login failed: username '', IP 162.158.69.157
2017-04-25 15:39:28,618 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_dmEdNJFpbKI.srt.sjson
2017-04-25 15:39:30,174 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-25 15:39:30,780 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_yFMCovOeHhs.srt.sjson
2017-04-25 15:39:31,278 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-25 16:44:08,539 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_dmEdNJFpbKI.srt.sjson
2017-04-25 17:52:53,376 INFO 787 [audit] models.py:1802 - Login success - user.id: 2
2017-04-25 17:54:42,562 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,582 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[4e845a92-5d0b-4691-bbf9-3312cf53cba6]
2017-04-25 17:54:42,595 INFO 790 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for Telos_Admin/FAKE_01/2017_Q2.
2017-04-25 17:54:42,628 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[4e845a92-5d0b-4691-bbf9-3312cf53cba6] succeeded in 0.0444699209183s: None
2017-04-25 17:54:42,662 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[4e35993a-384e-441c-9a09-219877c2430d]
2017-04-25 17:54:42,663 INFO 1006 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:54:42,676 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,676 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,676 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,676 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,676 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,677 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': SlashSeparatedCourseKey(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:42,681 INFO 1006 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: i4x://Telos_Admin/FAKE_01/course/2017_Q2
2017-04-25 17:54:42,706 INFO 1006 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:54:42,708 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[4e35993a-384e-441c-9a09-219877c2430d] succeeded in 0.0444838609546s: None
2017-04-25 17:54:58,831 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:58,866 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[1a52747e-6c96-4064-9b57-41f594e43487]
2017-04-25 17:54:58,918 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[1a52747e-6c96-4064-9b57-41f594e43487] succeeded in 0.0500114660244s: None
2017-04-25 17:54:58,927 INFO 790 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for Telos_Admin/FAKE_01/2017_Q2.
2017-04-25 17:54:58,992 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[0ec367bf-c0b7-4695-8c3d-229f324a93ff]
2017-04-25 17:54:58,994 INFO 1008 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:54:59,003 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,004 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,004 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,004 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,004 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,004 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:54:59,013 INFO 1008 [edx.celery.task] tasks.py:132 - Creating XBlockCache with usage_key: i4x://Telos_Admin/FAKE_01/chapter/6617c048e5974c128d5d8d6355b46ddc
2017-04-25 17:54:59,036 INFO 1008 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:54:59,037 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[0ec367bf-c0b7-4695-8c3d-229f324a93ff] succeeded in 0.0439618069213s: None
2017-04-25 17:55:07,769 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,806 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[3797b2aa-a71d-4eae-a332-612cab003561]
2017-04-25 17:55:07,844 INFO 790 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for Telos_Admin/FAKE_01/2017_Q2.
2017-04-25 17:55:07,851 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[3797b2aa-a71d-4eae-a332-612cab003561] succeeded in 0.0436242211144s: None
2017-04-25 17:55:07,889 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[10aff5c9-045a-4b14-9142-de783a75f5ba]
2017-04-25 17:55:07,891 INFO 1006 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,900 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:55:07,913 INFO 1006 [edx.celery.task] tasks.py:117 - Updating XBlockCache with usage_key: i4x://Telos_Admin/FAKE_01/chapter/6617c048e5974c128d5d8d6355b46ddc
2017-04-25 17:55:07,937 INFO 1006 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:55:07,938 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[10aff5c9-045a-4b14-9142-de783a75f5ba] succeeded in 0.0478772760835s: None
2017-04-25 17:57:00,589 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,625 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[4f1555e0-9196-418f-9d24-4f58b1cfa83c]
2017-04-25 17:57:00,664 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[4f1555e0-9196-418f-9d24-4f58b1cfa83c] succeeded in 0.037620031042s: None
2017-04-25 17:57:00,681 INFO 790 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for Telos_Admin/FAKE_01/2017_Q2.
2017-04-25 17:57:00,744 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[6bb931d9-d1da-4972-a876-0540e97bca2d]
2017-04-25 17:57:00,745 INFO 1008 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,758 INFO 790 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:57:00,762 INFO 1008 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:57:00,762 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[6bb931d9-d1da-4972-a876-0540e97bca2d] succeeded in 0.0176285789348s: None
2017-04-25 17:58:54,986 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent pre_publish signal to <function on_pre_publish at 0x7f00868b6b18> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,029 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[01f4030e-5467-4edd-bfd0-02c631bd637f]
2017-04-25 17:58:55,080 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.content.course_structures.tasks.update_course_structure[01f4030e-5467-4edd-bfd0-02c631bd637f] succeeded in 0.0494703068398s: None
2017-04-25 17:58:55,087 INFO 789 [openedx.core.djangoapps.content.course_overviews.models] models.py:120 - Creating course overview for Telos_Admin/FAKE_01/2017_Q2.
2017-04-25 17:58:55,150 INFO 570 [celery.worker.strategy] strategy.py:55 - Received task: openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[5daa1fb4-9374-4f6b-886c-c3fc695b3a6f]
2017-04-25 17:58:55,152 INFO 1006 [edx.celery.task] tasks.py:157 - Starting XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:58:55,161 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f00868acc08> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,161 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function listen_for_course_publish at 0x7f0082e5a320> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,161 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1758> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,162 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de1c80> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,162 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function trigger_update_xblocks_cache_task at 0x7f0082de7140> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,162 INFO 789 [xmodule.modulestore.django] django.py:116 - Sent course_published signal to <function _listen_for_course_publish at 0x7f0082de70c8> with kwargs {'course_key': CourseLocator(u'Telos_Admin', u'FAKE_01', u'2017_Q2', None, None)}. Response was: None
2017-04-25 17:58:55,168 INFO 1006 [edx.celery.task] tasks.py:159 - Ending XBlockCaches update for course_key: Telos_Admin/FAKE_01/2017_Q2
2017-04-25 17:58:55,169 INFO 570 [celery.worker.job] job.py:401 - Task openedx.core.djangoapps.bookmarks.tasks.update_xblock_cache[5daa1fb4-9374-4f6b-886c-c3fc695b3a6f] succeeded in 0.0178677667864s: None
2017-04-25 20:35:24,817 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_dmEdNJFpbKI.srt.sjson
2017-04-25 20:35:36,368 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-25 20:38:06,857 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-25 20:38:07,874 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_yFMCovOeHhs.srt.sjson
2017-04-25 20:43:44,565 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_mHJlt3w4kTQ.srt.sjson
2017-04-25 20:50:50,670 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-25 20:50:59,569 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_keIbb7Ch9Ic.srt.sjson
2017-04-25 20:51:18,748 INFO 787 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_qrmrCl7lbKA.srt.sjson
2017-04-25 21:45:15,106 INFO 788 [xmodule.video_module.video_handlers] video_handlers.py:242 - asset-v1:SkandalarisCenter+SCYC1001+SU_2017+type@asset+block@subs_keIbb7Ch9Ic.srt.sjson
2017-04-25 23:28:06,015 INFO 788 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): localhost
2017-04-25 23:28:06,025 INFO 788 [lms.lib.comment_client.utils] utils.py:49 - comment_client_request_log: request_id=9138cd22-a743-4e09-9ae8-e52800f490b8, method=get, url=http://localhost:18080/api/v1/users/2, duration=0.0106899738312
2017-04-25 23:28:06,036 INFO 788 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): localhost
2017-04-25 23:28:06,044 INFO 788 [lms.lib.comment_client.utils] utils.py:49 - comment_client_request_log: request_id=344cb23e-482b-41ea-926f-c2ed27ce1d74, method=get, url=http://localhost:18080/api/v1/users/2, duration=0.0085711479187
2017-04-25 23:28:06,045 INFO 788 [requests.packages.urllib3.connectionpool] connectionpool.py:203 - Starting new HTTP connection (1): localhost
2017-04-25 23:28:06,067 INFO 788 [lms.lib.comment_client.utils] utils.py:49 - comment_client_request_log: request_id=9100fd6c-54c7-460a-a5e7-e8a12dd06484, method=get, url=http://localhost:18080/api/v1/threads, duration=0.0226719379425
2017-04-25 23:28:12,497 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'equality_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,498 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'vertical_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,498 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'attempts_scoreboard_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,499 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'filethumbs'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,499 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'slider_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,500 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'helloworld_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,500 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'html_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,501 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'textinput_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,501 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'allscopes_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,502 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'debugchild'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,502 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'problem_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,502 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'sidebar_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,503 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'view_counter_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,503 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'sequence_demo'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,504 WARNING 787 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'thumbs'
Traceback (most recent call last):
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (Django 1.8.12 (/opt/bitnami/apps/edx/edx-platform/venv/lib/python2.7/site-packages), Requirement.parse('Django<1.5,>=1.4'))
2017-04-25 23:28:12,571 INFO 787 [edx.courseware] grades.py:314 - Signal fired when student grade is calculated. Receiver: <function listen_for_grade_calculation at 0x7f0085a12c08>. Response: None
